### ISSUE TITLE
🐛 [User-reported Bug]

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#54] opened 2019-11-26 22:19 UTC
Submitter: mike
Email: mike.xiao@childmind.org
this is the button to access the data panel between 'surveys' and 'about'. It works fine on IOS.

**Comment by hotavocado** [comment] 2020-01-19 18:29
Going into the data panel crashes the app when you haven't recorded any data for the applet, I think this is a known issue

**Comment by WorldImpex** [comment] 2020-01-19 19:49
duplicate of https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/625

**Closed by WorldImpex** 2020-01-19 19:49 UTC
Labels: MindLoggerbugreports, bug, user-reported
