### ISSUE TITLE
✨ Customized Target Questioning

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#19] opened 2019-03-20 15:12 UTC
As a manager/coordinator or user, I want to create a custom activity by selecting target or targets to ask the user, so that particular behaviors can be tracked as they change 

Description: When a clinician and patient are trying to track target behaviors, they will decide on what bad behaviors they are trying to mitigate and then add them to the activity for that patient. As the behaviors change over time, the user needs the ability to remove targets and add targets to the activity. This change should be recorded in the data as well as change the results of the assessment as well. Users can have 1 or more target behaviors at any given time. 

The use case in by @shnizzedy in the comments would be decided in a meeting with a manager/coordinator and the user. They would decide as a group that the user would need the nail-biting and nose picking target questioning for the user. The manager/ coordinator would apply those set of questions to that user within the applet. It would not change anything else for other users. 

Acceptance Criteria
Given I am a user with target questions setup
When a manager/coordinator makes changes to someone else's applet
Then nothing changes for my applet 

Given I am a user 
When I decide with a manager/coordinator what target questions I need
Then the manager/coordinator setups a custom applet for me 

Given I am a manager/coordinator 
When I manage my user's custom applets
Then I can make changes to each one individually

**Comment by Eden2016** [comment] 2019-12-20 14:05
Not clear what should be done from the front-end perspective.
What user's flow is related to this issue?

**Comment by shnizzedy** [comment] 2020-01-06 21:49
The particular activity that this issue is intended to facilitate has a pair of screens in which `(Target 1)` would need to be replaced by one of a user's specific targets for each of that user's specified targets.

Prompt | Options
--- | ---
Did you have an urge to engage in (Target 1) today? | 0=No urge,1=Fleeting urge, 2=Some urges,  3=Moderate urge,  4=Strong urge,  5=Very strong urge
Did you act (Target 1) urges today? | 1=No, 2=Yes

For example, if an individual's targets are "nose picking" and "nail biting", they should get these four questions:

1. Did you have an urge to engage in nose picking today?
2. Did you act on nose picking urges today?
3. Did you have an urge to engage in nail biting today?
4. Did you act on nail biting urges today?

If a target "swearing at strangers" is added, that section should expand to 6 screens:
1. Did you have an urge to engage in nose picking today?
2. Did you act on nose picking urges today?
3. Did you have an urge to engage in nail biting today?
4. Did you act on nail biting urges today?
5. Did you have an urge to engage in swearing at strangers today?
6. Did you act on swearing at strangers urges today?

And then when the individual has overcome nose picking and that target is removed, the section should contract to 4 screens:

1. Did you have an urge to engage in nail biting today?
2. Did you act on nail biting urges today?
3. Did you have an urge to engage in swearing at strangers today?
4. Did you act on swearing at strangers urges today?

As the title of this issue says, "everyone's targets are unique", so changes in one user's targets should not affect other users of the same applet/protocol/activity/screen, and users without any targets should not see the questions that include `(Target 1)`.

**Comment by shnizzedy** [comment] 2020-01-06 21:59
> Not clear what should be done from the front-end perspective.
> What user's flow is related to this issue?

The flow is complicated and this issue should probably be separated into multiple issues as the components of the flow are tackled:

[![DBT diary card user journeys](https://childmindinstitute.github.io/MATTER-spec-docs/MindLogger/diagrams/user-journey/DBT.png)](https://childmindinstitute.github.io/MATTER-spec-docs/MindLogger/DBT-daily-diary-card.html#user-journeys)

**Comment by WorldImpex** [comment] 2020-02-03 13:32
Capturing this from the description 

For DBT Diary Card, 

> -  Would everyone have exactly 3 targets?
>    – some people could have more and some people could have less – is it possible to activate more or less targets as needed? How would we do that?
> - Would everyone have unique targets, or would groups have the same targets as each other?
>    – everyone’s targets are unique and some change over time – it would be important to be able to change the target descriptions and be able to identify when that change happened from a data collection stand point
> - Do the targets change over time?
>     – yes (see above)
> - Are the targets always set by the clinician, or can the patient choose them?
>     – the targets are chosen collaboratively in session so it would be decided by clinician and patient
> - How would you like to see these targets customizable?
>     – yes! If the patient or the clinician can go in and change the target that would be ideal

Related ChildMindInstitute/MindLogger-bug-reports#17

**Comment by WorldImpex** [comment] 2020-02-06 16:47
duplicate of #749

**Closed by WorldImpex** 2020-02-06 16:47 UTC
Labels: Epic, backend, enhancement, good first issue, small scope
